# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-powershell-reviewer-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  testing:
    uses: ./.github/workflows/testing_stage.yml

  build:
    runs-on: 'ubuntu-latest'
    needs: testing

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acrpowershellreviewerprod.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3cbd9f2f1e4d49438916325d0a9691ca }}
        password: ${{ secrets.AzureAppService_ContainerPassword_31af917c00b5417d80758da21e425965 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acrpowershellreviewerprod.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3cbd9f2f1e4d49438916325d0a9691ca }}/powershell-code-reviewer:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: [testing, build]
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-powershell-reviewer-prod'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cbb61d5593fe4307905f2b3c3297ae17 }}
        images: 'acrpowershellreviewerprod.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3cbd9f2f1e4d49438916325d0a9691ca }}/powershell-code-reviewer:${{ github.sha }}'