name: Pipeline Testing

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies and run tests
      run: |
        pip install -r requirements.txt
        pytest -v
        bandit -r app

    - name: Build and scan Docker image
      run: |
        docker build -t temp-scan .
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy:latest image --severity HIGH,CRITICAL temp-scan
    